version: '3.9'

services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - ./:/app
    command: npm run dev
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker
      NODE_OPTIONS: "--max-old-space-size=1200"  # Adicione esta linha
