version: "3.9"

services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - ./:/app
    command: npm run prisma
    ports:
      - "3005:3005"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker
      NODE_OPTIONS: "--max-old-space-size=1200"
      DATABASE_URL: "sqlserver://sqlserver:1433;database=residenteDB;integratedSecurity=true;username=sa;password=Xr09LDtRhyW3LkiI;trustServerCertificate=true;encrypt=true;IntegratedSecurity=false;"
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_express
    restart: always
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_database:/var/opt/mssql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'Xr09LDtRhyW3LkiI' -Q 'SELECT 1'",
        ]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  sqlserver_database:
