name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWD }}
        
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.4.1
        with:
          context: .
          push: true
          tags: |
            ${{secrets.DOCKER_USERNAME}}/backend-web:latest
            ${{secrets.DOCKER_USERNAME}}/backend-web:${{ github.run_number }}
